# 4장 예외

자바 예외처리 접근 방법에 대해서 알아보자

## 4.1 사라진 SQLException

jdbcTemmplate에서 사라진 SQLException.

```java
public void deleteAll() {
	this.jdbcTemplate.update("delete from users");
}
```

### 4.1.1 초난감 예외처리

case 1. 빈 catch 문 - 오류의 원인을 알수가 없다. 원인을 찾아내기 너무 힘들어진다.

```java
try {
	...
} catch(SQLException e) {

}
```

case 2. 오류 단순 출력 - 콘솔 로그를 들여다보고 있지 않는한 해결하기 어렵다

```java
}catch (SQLException e) {
	System.out.println(e);
}

}catch (SQLException e) {
	e.printStackTrace();
}
```

굳이 예외를 잡아서 조치할 방법이 없다면, catch로 잡지마라. 메소드에 thorws SQLException을 선언해서 메소드 밖으로 던지고 자신을 호출한 코드에 예외처리 책임을 전가해라

**무의미하고 무책임한 throws**

```java
public void method1() throws Exception {
	method2();
}

public void method2() throws Exception {
	method3();
}

public void method3() throws Exception {
	method2();
}
```

정확하게 예외 이름을 적기 귀찮으니 thorws Exception으로 처리해버린다.

이런케이스도 심각한 문제가 있다. 적절한 처리를 통해 복구할 수 있는 상황도 처리할 수 있는 기회를 놓친다. 

### 4.1.2 예외의 종류와 특징

체크 예외를 다루는 방법.

자바에서 throw를 통해 발생시킬 수 있는 예외는 크게 세가지가 있다.

1. Error (java.lang.Error)
    
    VM에서 발생하는 에러로, 코드단에서 잡을 수 없다. 애플리케이션에서 신경쓸 수 없는 에러들이다.
    
2. Exception과 체크 예외 (java.lang.Exception)
    
    개발자들이 만든 애플리케이션 코드의 작업 중, 예외상황이 발생했을 경우에 사용된다.
    
    - 체크 예외
    - 언체크 예외 (RuntimeException 클래스 상속)
    
    체크 예외는 catch문으로 잡든지 아니면 thorws를 사용하여 메소드 밖으로 던져야한다.
    
3. RuntimeException과 언체크/런타임 예외 (java.lang.RuntimeException)
    
    명시적 예외처리를 강제하지 않는다. 명시적으로 잡거나 throws로 선언해줘도 상관없다. 프로그램에 오류가 있을 때 발생한다. ex) NPE, IllegalArgumentException.
    
    이런경우는 프로그래머가 주의깊게 개발한다면 피할 수 있다. 따라서 굳이 catch나 throws를 사용하지 않아도된다.
    

### 4.1.3 예외처리 방법

예외처리를 하는 일반적인 방법을 보고 효과적인 예외처리 전략을 생각해보자

**예외복구**

사용자가 읽으려는 파일이 없거나 문제가 있어 읽히지 않아 IOExeption이 발생한경우 다른 파일을 이용하도록 안내해서 예외상황을 해결 할 수 있다.

혹은 네트워크가 불안해서 가끔 접속에 오류가 있어 SQLException이 발생하는 경우, 재시도를 시도하거나 일정시간 대기 후 접속을 유도하는 방법을 사용해서 예외상황을 복구 할 수 있다. 

```java
int maxretry = MAX_RETRY;
while(maxretry --> 0) {
	try {
		...
		return;
	} catch(SomeException e) {
		//로그 출력. 정해진 시간만큼 대기 
	} finally {
		//리소스 반납. 정리 작업
	}

} 
throw new RetryFailedException(); //
```

**예외처리 회피**

예외처리를 던지는 방법이다.

throws로 던지거나, catch로 예외를 잡은 후 로그를 나믹고 다시 예외를 던지는 것이다. 예외처리를 회피하려면 반드시 다른 오브젝트나 메소드가 예외를 대신 처리 할 수 있도록 던져줘야한다.

예외를 회피하는 것은 예외를 복구하는 것 처럼 의도가 분명해야한다. 예를 들면 긴밀하게 역할을 분담하고 있어 해당 에러를 처리하는것은 발생 계층이 아니라 다음 계층일때와 같은 경우다. 무책임하게 예외를 서비스 계층으로 던지고 컨트롤러 계층으로 던지면 안된다.

**예외 전환**

예외 회피와 마찬가지로 예외를 던지는 것인데, 그대로 던지는 것이아니라 적절한 예외로 전환해서 던지는 것이 특징이다.

예외 전환은 두가지 목적에서 사용된다.

1. 의미를 분명하게 해줄 수 있는 예외로 바꿔주는 경우
    
    예를들면 중복 사용자를 등록할 때 SQLException이 났다면, Business Exception으로 전환해서 throws 한다. DuplicateUserIdException 등..
    
    ```java
    public void add(User user)throws DuplicateUserIdException, SQLException {
    	try {
    		
    	} catch(SQLException e) {
    		if(e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
    			throw DuplicationUserIdException();
    			//throw DuplicationUserIdException(e);
    			//throw DuplicationUserIdException().initCause(e);
    		else
    			throw e;
    	}
    
    }
    ```
    
    주석처럼 원래 발생한 예외를 담아서 중첩 예외로 만드는 것이 좋다. getCause()를 통해서 처음 발생한 예외가 무엇인지 알 수 있다.
    
2. 예외처리를 강제하는 체크 예외를 언체크 예외인 런타임 예외로 바꾸는 경우
    
    의미를 명확하게 하려고 다른 예외로 전환하는 것이 아님. 중첩 예외를 통해 원 예외를 wrap하는 것은 동일
    
    예를들어 EJB 컴포넌트에서 발생하는 복구 불가능한 예외는 런타임 예외인 EJBException으로 포장해서 throw한다.
    
    체크예외를 계속 throws를 사용해 넘기는건 무의미하다. 예를들어 SQLException의 경우 DAO에서 발생한 Exception을 Controller로 넘긴다고해도 처리할 방법이 없다. 이럴때는 가능한 런타임 예외로 포장해서 던지고 다른 계층에 throws 선언이 들어가지 않도록 해줘야한다. → 이해가 안된다. 그럼 그냥 코드 실행도중에 발생하면 어떻게 함?
    
    어짜피 해결을 못하면 런타임 예외로 포장해서 던지고, 자세한 로그를 남기고, 관리자등에게 메일로 통보를 해주고, 사용자에게는 친절한 안내 메시지를 보여주는 식으로 처리하는게 바람직하다.
    

### 4.1.4 예외처리 전략

예외가 발생하는 코드를 깔끔하게 정리하는데에 신경써야할 것들이 많다. 일괄된 예외처리 전략을 정리해보자

**런타임 예외의 보편화 → 잘 이해되지 않음.**

자바 엔터프라이즈 서버환경은 하나의 시스템을 다수의 사용자가 동시요청 보내고 사용하고 있으므로, 예외가 발생했을 경우 해당 작업을 중지시키는 편이 좋다. 따라서 애플리케이션 차원에서 예외상황을 미리 파악, 발생하지 않도록 차단하는게 가장좋다.

따라서 처리가 불가한 체크예외는 빨리 런타임 예외로 전환해서 던지는 것이 좋다.

**add() 메소드의 예외처리**

상기의 DuplicatedUserIdException을 굳이 체크 예외로 둘필요가 없다. 어디서든 처리할 수 있다면 런타임 예외로 만드는 것이 낫다. 다만, add() 메소드에 명시적을 DuplicatedUserIdException을 던진다고 선언해야한다. 그래야 add()메서드를 호출하는 개발자에게 의미있는 정보를 전달 해줄 수 있다. 런타임 예외도 throws로 선언할 수 있다.

```java
public class DuplicatedUserIdException extends RuntimeException {
	public DuplicatedUserIdException****(****Throwable cause) {
		super(cause);
	}
}
```

```java
public void add()throws DuplicateUserIdException {
	try {
		
	} catch(SQLException e) {
		if(e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
			throw DuplicationUserIdException(e);
		else
			throw new RuntimeException(e); //예외포장
	}
}
```

이제 위 add()메소드를 사용하는 오브젝트는 SQLException을 사용하기 위해 불필요한 throws 선언을 할 필요가 없다. 다만, 컴파일러가 예외처리를 강제하지 않았기 때문에 신경쓰지 않으면 예외상황을 충분히 고려하지 않을 수 있다. 메소드를 사용할 때 발생할 수 있는 예외의 종류와 원인, 활용 방안을 자세히 설명해두어야한다.

**애플리케이션 예외**

애플리케이션 자체의 로직에 의해 의도적으로 발생하고 반드시 catch해서 조치를 취하도록 요구하는 예외를 애플리케이션 예외라고한다.

예를들어 예외를 처리하는 방법에 두가지가 있는데, 첫번째는 리턴값으로 일종의 결과 상태를 리턴하는 것이다. 예외가 발생하지 않고, 원치않는 결과라면 0 혹은 -1, -999같은 결과를 리턴하고, 정상처리 케이스에서는 정상결과값을 리턴한다. 이런경우는 두 경우 모두 정상흐름이므로 오류라고 볼 수 없으나, 원치않는 결과의 정의를 제대로 해놓지 않으면 이것이 정상처리된 결과인지 오류인지, 어떤 오류인지 파악하기 어렵다. 또 if 구문이 많아지기때문에 코드가 더러워진다.

두번째 방법은 예외상황에서는 비지니스 예외를 던지는 것이다. 해당 메서드를 호출하는데에 호출 후 catch 블록을 둘 필요 없이, 메소드 내부에서 예외는 의도적으로 체크 예외를 만들고 처리한다. 

```java
try {
	BigDecimal balance = account.withdraw(amount);
} catch(InsufficientBalanceException e) {
	
	BigDecimal availFunds = e.getAvailFunds();
	//잔고 부족 아내 메시지를 준비하고 출력 및 남은 잔고 안내
}
```

### 4.1.5 SQLException은 어떻게 됐나?

그래서 JdbcTemplate의 throws SQLException은 왜 사라졌을까? SQLException은 사용자가 코드단에서 조치를 취할 방법이 없다. 개발자에게 빨리 예외가 발생했다는 사실이 알려지도록 전달하는 방법밖에 없다. 

따라서 빨리 언체크/런타임 예외로 전환해줘야한다. 

JdbcTemplate은 이 전략을 따라서 런타임 예외인 DataAccessException으로 포장해서 던져준다. JdbcTemplate을 사용하는 UserDao에서는 필요하면 DataAccessException을 잡아서 처리하고 그 외는 무시한다. 따라서 DAO메서드에서 SQLException이 모두 사라진것이다.
